### PR TITLE
Add other instruments, checks, and parsing options

### PR DESCRIPTION
**Pull request by TheNathannator**
Major changes:
- Organized files into folders
- Added drums, vocals, pro guitar, and pro keys
- Added various parameters to enable/disable checks

### CODE REVIEW

**Comment by GenericMadScientist** [comment]
Alright, I've looked this over and here are my comments and requested changes.

General remark: please remove commented-out code and invalid enum values, they don't serve any purpose. Besides, we have it in version control if we need it again.

For the large collection of options, I'm wondering if we could not just bundle them together under some form of `-a/--all` option. Is there a use case where we want to specifically only enable a subset of the ones you added? And I am keen to keep the default optimised for checking if rips need fixing.

In `CHSong.cs`, you do a pattern of iterating over the keys of a dictionary then just using that to look up the value. However, you can [iterate over the values directly](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.idictionary-2.values?view=net-6.0).

In `GuitarTrackNotes.cs`, can we make `trackWarnings` a `readonly` variable?

`GuitarTrackNotes.cs` should be renamed to `GuitarTrackNote.cs` since you've changed the enum name (and I think making it singular is a good change). Similarly, should we not also use the singular for drum, pro guitar, pro keys, and vocal notes?

I'm not sure what the use case for having the chord snapping check function is for `ProKeysTrack`. And for the switch statement that gets the difficulty from the track name, maybe we should have a warning or something in a `default` case? Or is there some reason that can never get triggered that I'm not seeing?

For `VocalsTrack.cs`, I would be happier if `phrases` were a property or if it were made private and the overload of `RunChecks` just took in the entire HARM2 track. Also very minor note but at L34 I believe it would be better as an `else if`.

That's all the quibbles I have. Nice work.

**Comment by TheNathannator** [comment]
Removed those unnecessary comments.

Maybe we could add a couple presets of options for different types of rips (GH, RB)? I added these options since some of these can get pretty spammy, which is inconvenient if you're just looking for a specific issue that isn't the one being spammed.

Don't know why I didn't think of using the values instead of the keys in `CHSong.cs` lol, thanks for pointing that out. Also added a `Name` property to all the tracks for the cases that I do need the name.

Went and made all `trackWarnings` readonly, and renamed all `TrackNotes` to `TrackNote`, including file names. Also copied the inverse order comment to all of them.

For chord snapping, I was told that any track that can be chord snapped, should be. In fact, here's an example of Pro Keys chord snapping (RB3's `Amy Winehouse - Rehab`, 1 tick start and end gap):
image

Made the vocals track `phrases` a property, and did the `else if`. Also had to catch an exception for multiple lyrics that occur at the same position

Added a `Debug.WriteLine` to print the path of the current .mid being checked.

I think that that's everything I did, lemme know what you think.

**Comment by GenericMadScientist** [comment]
Provided RB3 snaps that chord, then yes definitely keep the pro keys chord snapping check. In hindsight I was getting confused with disjoint chords, something that does exist on keys.

For the options I think it best to organise it around use cases. The two that come to mind immediately are checking rips (which ideally is the default) and looking for everything odd. By checking rips I merely mean what is relevant to Clone Hero, so for example the default wouldn't check anything on pro keys. Is checking for one specific thing anyone is likely to want to do? What other use cases are there?

Lastly, feel free to add your name to the license and csproj files. You've certainly contributed enough to warrant it.

**Comment by TheNathannator** [comment]
Will do so, thanks.

I've decided to remove the individual options, and also removed the if()s for things that should be checked regardless (chord snapping, lyrics alignment/phrases). Then I moved the parsing options to a separate class, removed the now-unused settings, and added a Pro instruments setting. The settings I have currently now are unknown notes, disjoints, and Pro instruments.

The parameters I'm adding now are CheckAll (enables checking of Pro instruments and unknown notes), RBPro (enables checking of Pro instruments), and GHBand (excludes the disjoint chord check for GHWT and onward songs). CheckAll overrides both GHBand and RBPro, and both GHBand and RBPro can be used at the same time. The defaults just have disjoints enabled.

Do those seem fine?

**Comment by GenericMadScientist** [comment]
Yep, that looks good to me.

**Pull request merged**
